apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-repo-service
spec:
  selector:
    app: spring-boot-app-repo-service
    type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080